import type { NextPage } from "next";
import Head from "next/head";
import LeftNav from "@common/navigation/LeftNav";
import MainToolbar from "@common/navigation/MainToolbar";
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Toolbar from '@mui/material/Toolbar';
import HomeIcon from '@mui/icons-material/Home';
import PeopleIcon from '@mui/icons-material/People';
import RodeoDashboard from "@features/RodeoDashboard/RodeoDashboard";
import { PLACEHOLDER_RODEOS } from "src/content/mockData";

const IndexPage: NextPage = () => {
  const leftNavWidth = 240;
  const leftNavMenuItems = [{
    text: 'Home',
    icon: <HomeIcon/>
  }, {
    text: 'Rodeos',
    icon: <HomeIcon />
  }, {
    text: 'Participants',
    icon: <PeopleIcon />
  }]


  return (
    <div>
      <Head>
        <title>Rode.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hat-md.png" />
      </Head>

      <Box sx={{ display: 'flex' }}>
        <CssBaseline />
        <MainToolbar leftNavWidth={leftNavWidth}/>
        <LeftNav 
          menuItems={leftNavMenuItems}
          width={leftNavWidth}
        />

        {/* app body */}
        <Box
          component="main"
          sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3 }}
        >
          <Toolbar/>

          {/* (actual app body contents) */}
          <RodeoDashboard
            rodeos={PLACEHOLDER_RODEOS}
          />
        </Box>
      </Box>
    </div>
  );
};

export default IndexPage;