const Head = () => {
  return (
    <>
      <title>Rode.io</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/hat-md.png" />
    </>
  )
}

export default Head;